# Generated by Django 6.1 on 2026-09-18 05:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit identifier', max_length=64, unique=True)),
                ('barcode', models.CharField(blank=True, default='', help_text='Barcode / EAN identifier', max_length=64)),
                ('name', models.CharField(db_index=True, help_text='Full product title', max_length=255)),
                ('brand', models.CharField(db_index=True, help_text='Brand name', max_length=128)),
                ('category', models.CharField(db_index=True, help_text='Primary category name', max_length=128)),
                ('subcategory', models.CharField(blank=True, default='', help_text='Secondary category or product type', max_length=128)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Current effective customer selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.IntegerField(default=0, help_text='Current available inventory quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.TextField(blank=True, default='', help_text='Product image URL or relative path')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Key-value specifications object')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'category'], name='products_pr_brand_b6066d_idx'), models.Index(fields=['selling_price'], name='products_pr_selling_77a2d1_idx')],
            },
        ),
    ]
